name: Build libav.wasm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache build
      id: cache-build
      uses: actions/cache@v3
      with:
        path: build-cache
        key: build-cache
    - name: Build libav.wasm
      run: bash build.sh --cache-from=type=local,src=build-cache --cache-to=type=local,dest=build-cache,mode=max
    - uses: actions/upload-artifact@v3
      with:
        name: libav.wasm
        path: dist
