name: Build libav.wasm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache build
      id: cache-build
      uses: actions/cache@v3
      with:
        path: build-cache-v1
        key: build-cache-v1-${{ hashFiles('Dockerfile*') }}
        restore-keys: |
          build-cache-v1-
    - name: Build libav.wasm
      run: make ci
    - uses: actions/upload-artifact@v3
      with:
        name: libav.wasm
        path: dist
