name: Build libav.wasm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2
    - name: Cache build
      id: cache-build
      uses: actions/cache@v3
      with:
        path: build-cache-v1
        key: build-cache-v1-${{ hashFiles('Dockerfile*') }}
        restore-keys: |
          build-cache-v1-
    - name: Build libav.wasm
      run: |
        EXTRA_CFLAGS="-O3" \
        EXTRA_LDFLAGS="-O3" \
          bash build.sh --build-arg EXTRA_CFLAGS --build-arg EXTRA_LDFLAGS \
          --cache-from=type=local,src=build-cache --cache-to=type=local,dest=build-cache,mode=max
    - uses: actions/upload-artifact@v3
      with:
        name: libav.wasm
        path: dist
