name: Build libav.wasm

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: bash build.sh --cache-from=type=gha --cache-to=type=gha
    - uses: actions/upload-artifact@v3
      with:
        name: libav.wasm
        path: dist
